[project]
name = "ytdla"
version = "0.1.0"
description = "Opinionated script for downloading audio from youtube using yt-dlp under the hood"
authors = [
    {name = "Lunar", email = "lunarlifeburst@gmail.com"},
]
dependencies = [
    "yt-dlp",
    "yt-dlp-ejs"
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[project.scripts]
ytdla = "ytdla:main"